### ISSUE TITLE
User can enter zip code

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#1]
As a recycler, I would like the mobile application to store entered zip code data, so that Live Thrive can store data on where recyclers live.

Scenario 1: A recycler wants to enter the zip code
Given: the user is on the mobile application's main page to enter recycler information;
When: a zip code is entered and the submit button has been pressed;
Then: the zip code is stored in the database.

Scenario 2: A recycler wants to change their mind on entering the zip code
Given: the user is on the mobile application’s main page page to enter recycler information;
When: their zip code is entered and the user changes their mind and the  submit button is not pressed;
Then: the zip code is not stored in the database.

**Comment by lkm027** [comment]
This issue was addressed in commit efb8fbb6d6429242b32e755ea373badfaab6a4da. Going forward issues will be closed with pull requests to make it easier to view changes.
