### ISSUE TITLE
Employee can navigate web app

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#15]
As a Live Thrive employee, I would like to be able to navigate web app, so that I can easily view and analyze the data.

Scenario 1: A Live Thrive employee would like to be able to simply view and analyze data
Given: the employee is on the page that displays the collected data on the web application;
When: the graph/table display button is clicked;
Then: a graph/table will show the employee items recycled.

Scenario 2: A employee would like to be able to view graphs regarding the demographics of the users
Given: a employee is on the analytics page of the web application;
When: the employee clicks the generate button;
Then: the statistics will be displayed with no additional text boxes or information to process.

**Comment by lkm027** [comment]
This is an invalid issue. This should be for the web app
