### ISSUE TITLE
Add unit to the items that can be recycled

### ISSUE THREAD

**Issue by lkm027** [JID8201/CHaRM-Android-App#17]
This issue is supposed to add the unit of measurement to the item being recycled on the recycle screen. This is to help the user understand what they should be putting their amount of items with respect to.

@distroJack 

Do you know if we have the associated measurement units for these items? I also noticed that the donation items listed on the home screen and the ones that you can choose to recycle are different. Are they supposed to be different? I just want to make sure.

When you get those units can you update or comment on this ticket with them? Thank you.

**Comment by opowell26** [comment]
I also need this info

**Comment by lkm027** [comment]
This item was addressed in commit c301498.

Units have been added to the spinner and to the list of items to be recycled.
