### ISSUE TITLE
User can access home page

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#2]
As a recycler, I would like the the mobile application to include a main page, so that I can reach all parts of the application easily.

Scenario 1: A recycler wants to go on the home page when they open the mobile application
Given: the recycler has opened the mobile application;
When: they have finished entering their personal information details on the mobile application such as zip code, phone number etc;
Then: they are redirected to the home page where they can reach all other parts of the application with ease. 

Scenario 2: A recycler wants to go on the home page when they are on another part of the mobile application
Given: the recycler is on another part/ tab of the mobile application;
When: they click on the “Home” button on the mobile application;
Then: they are redirected to the home page where they can reach all parts of the application easily.

**Comment by lkm027** [comment]
This issue was addressed in commit 9fff3de596dc9b60f828956f73507d4d6f090e2a. Going forward these will be closed with pull requests that allow for direct access.
