### ISSUE TITLE
User can enter type of item being recycled

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#3]
As a recycler, I would like to be able to specify the category of the item I am recycling, so that Live Thrive has data on the number of each type of recycling item.

Scenario 1: A recycler wants to specify the category of recycled items
Given: the recycler is on the page to enter information on the mobile application;
When: a category is chosen by the user from a drop-down menu;
Then: the category will be tallied in the database for future reference.

**Comment by lkm027** [comment]
This issue was addressed with commit 8ab9aee0850a823fe441425a6d2f7cdb911119e3. Going forward issues will be closed with a pull request to allow for easier access.
