### ISSUE TITLE
User can enter info on item being recycled

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#4]
As a recycler, I would like a text box, so that I can enter a specific description about the item.

Scenario 1: A recycler wants to add a description about an item
Given: a recycler clicks an item on the mobile application;
When: enters data in the text field that pops up;
Then: the description is saved for that item.

Scenario 1: A recycler wants to erase a description about an item
Given: a recycler clicks an item on the mobile application;
When: erases the content of the text field that pops up;
Then: the description is cleared for that item.

**Comment by lkm027** [comment]
This issue was addressed with commit a95ef71be93c465d7cbd0e9f9cc5dba101252ad5. Going forward issues will be closed with a pull request to allow for easier access.
