### ISSUE TITLE
User can find useful information about live thrive

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#5]
As a recycler, I would like a page that displays useful information on Live Thrive, so that I can retrieve Live Thrive’s contact information and understand what items can be recycled at Live Thrive.

Scenario 1: A recycler would like a page that displays useful information on Live Thrive when they open the mobile application first. 
Given: the recycler opens the mobile application;
When: they are directed to the initial homepage;
Then: a section on the homepage will display information about Live Thrive. 

Scenario 2: A recycler would like a page that displays useful information on Live Thrive when they are on a separate page entering their zip code and personal information
Given: the recycler is on a different page than the homepage on the mobile application;
When: they click on the “Home” tab/ button in the sidebars of the mobile application;
Then: they will be directed to the homepage where here will be a section which displays information about Live Thrive.

**Comment by lkm027** [comment]
This issue was addressed in commit 3ffed5caccb37e237a18b08e6aded1b393fe0043. Going forward these issues will be closed with pull requests to make it easier to review.
