### ISSUE TITLE
User can use donation page

### ISSUE THREAD

**Issue by bran100** [JID8201/CHaRM-Android-App#9]
As a Live Thrive employee, I would like a donation page on the mobile application, so that I can receive donations from recyclers.

Scenario 1: A recycler would like to donate money to Live Thrive. 
Given: the recycler is on the main page on the mobile application;
When: they click on the “Donation” button;
Then: the recycler is directed to the donation page where the recycler can make donations to Live Thrive.

**Comment by lkm027** [comment]
This was finished and completed with pull request #14.
